### ISSUE TITLE
Product attributes are created as Products

### ISSUE THREAD

**Issue by dreispt** [OCA/product-configurator#10]
Observed this. The list of products is polluted with items that are not products, but Attribute values.

![image](https://user-images.githubusercontent.com/1246629/116382181-8dae8c80-a80d-11eb-8d29-7f00009c38c7.png)

**Comment by bizzappdev** [comment]
Basically, it is a feature for the BOM and many other things. For each attribute value, you can configure the related product.
which will be used for a different purpose. like, create BOM etc.
