### ISSUE TITLE
Dynamic BoM not working (or working as expected)

### ISSUE THREAD

**Issue by ddavis-osi** [OCA/product-configurator#20]
Recreate: Create configurable product -> add variant attributes -> create BoM -> add two lines that use "configuration set" to restrict the BoM upon variant creation -> configure product -> check new BoM created for variant (it is empty)

![image](https://user-images.githubusercontent.com/68346177/119170039-b43c9d80-ba30-11eb-9d29-836921aea912.png)

expected behavior: The new variant BoM should have created the components that matched the configuration set config of the master BoM.

**Comment by patrickrwilson** [comment]
PR #28 had some improvements to address this issue. @ddavis-osi this issue is solved, can you please close it? Thanks.
