### ISSUE TITLE
Backend configurator refactoring

### ISSUE THREAD

**Issue by PCatinean** [OCA/product-configurator#4]
When this project started out the website module was not that mature and neither was qweb. This meant that the standard views were used with tons of hacks on fields_get and fields_view_get. It was already difficult to maintain but now with the website configurator gaining a lot more traction, keeping both in sync is a tedious and time consuming task.

As such the backend wizard should be refactored to load a qweb view that will be re-used in the frontend and drop the old design completely. Since we have to re-build logic from the backend to the frontend (onchanges, domain restrictions) we might as well just do it for the backend also and have less work alltogether.

**Comment by dreispt** [comment]
There are a lot of configurator out-of-the box features that were not available when Pledra started.
IMP a refactoring should start but building on top of the v14 OOB configurator.

**Comment by PCatinean** [comment]
Yes that was the plan, to migrate to V14 as-is and then refactor in a separate branch. While we could in theory delay refactoring to V15 we already did this plenty of times and some of these issues are technical debt which are causing problems in a few production databases. We will see what the effort is and if it's too great we can postpone but I would try at least from my side to reconstruct a few of the concepts in order to solve some issues with existing customers.

**Comment by dreispt** [comment]
If you can split the refactoring into v14 incremental steps that would be great.
Bringing back the commented test cases would also be useful for this.
