### ISSUE TITLE
Issue with config session not created/ displaying in sales order line odoo 14 enterprise

### ISSUE THREAD

**Issue by Woodlawnfurniture** [OCA/product-configurator#43]
After configuring products in website and adding it to cart a config session is created and sale order is added in Odoo community
edition below image shows community edition outcome
![Odoo community](https://user-images.githubusercontent.com/79715303/126391795-9b813c01-17c6-4dbe-85f4-1d70ec6316bf.JPG)

In the other hand going throgh the same proccess config session is created but no config session nummber added to sales order line see below
![Odoo enterprise](https://user-images.githubusercontent.com/79715303/126392968-1494e81f-f172-4f86-ab5e-fd5af88e6433.JPG)

Any suggestions
Thank you

**Comment by PCatinean** [comment]
Hi, we were not able to reproduce this issue and we have the session attached on both versions (there should be nothing really in enterprise that interfeers with it). Can you reproduce this on a vanilla V14, can you share the reproduction steps?

**Comment by Woodlawnfurniture** [comment]
Hi, after further investigation we discovered it was an issue that occurs when products have "Optional Products" selected. This "Optional Products" section was being added by our theme (Theme Prime), not product configurator. When this section is left blank config session is created and added properly.
![Capture](https://user-images.githubusercontent.com/79715303/126521688-2a3a7d31-5f19-4bf2-8de1-393dd3fad8ba.PNG)
