### ISSUE TITLE
Configuration session refactoring

### ISSUE THREAD

**Issue by PCatinean** [OCA/product-configurator#5]
Having a configuration session stored in the database is mandatory especially with more advanced cases i.e complex configurations. However having draft sessions (incomplete sessions from backend or frontend public user) stored in the database is not that good of a design. For one it puts high strain on the database (every change from every public user in the frontend triggers first a creation of a session and subsequently a write in the config session / db). Second, cleaning up these sessions from the database as the volumes increase causes a lot of issues.

A refactoring is in order to transfer at least the draft configuration sessions to http sessions and manage domain restrictions / validation / price computation etc without the use of database persistence.

**Comment by dreispt** [comment]
Why not use a Transient Model - they are there for this kind of use cases.
It would even simplify current design:  a wizard record *is* a config session.

**Comment by PCatinean** [comment]
We are using the same configuration sessions for website as well and even if we used TransientModel when you have public traffic opening up configuration pages (includinig bots scraping and the lot) that is still translated to DB writes. We also want to keep config sessions alive if http sessions are there (so they don't loose config progress if they come back later) and also remove the config sessions when the http sessions are gone. We have many issues where we need to delete in bulk huge chunks at once and I don't think TransientModels will help here, I have considered them from the start though.
