### ISSUE TITLE
product_configurator BUG

### ISSUE THREAD

**Issue by DonatasV** [OCA/product-configurator#66]
product_configurator module breaks the original `weight` field of `product.product` and `product.template` models. So all standard SQL reports (e.g. `sale.report`, `purchase.report`) where is used product weight works incorrectly

## Module
product_configurator
`
## Describe the bug
stored field `weight` turns to non stored

## To Reproduce
**Affected versions**: 14.0

1. Create a new `test001` product with a weight of 10kg
![pic1](https://user-images.githubusercontent.com/38809768/168588113-d28fa025-beb1-4d6a-914b-e0026a9c538f.png)

2. Create a purchase order with product `test001`
![pic2](https://user-images.githubusercontent.com/38809768/168588234-ee55a845-9e5a-444b-9a8a-71f451f29a94.png)

3. Open standard purchase report
![pic3](https://user-images.githubusercontent.com/38809768/168588325-19fa4418-a28e-4747-9357-304b23b1f6e4.png)

**Expected behavior**
`Gross Weight` should be 10kg

**Comment by gaikaz** [comment]
@patrickrwilson 
Hi, could you please give this a look?
This breaks a lot of integrational tests.
