### ISSUE TITLE
Custom Attributes on Configurable Components

### ISSUE THREAD

**Issue by hagen-larsen-hl** [OCA/product-configurator#73]
## Module
product_configuator_mrp_component

## Describe the bug
When a product has custom attributes and configurable components, the configurable components must contain the same custom attributes as the parent product.

## To Reproduce
**14.0**

1. Create a product with a custom attribute
2. Create a configurable component with no custom attributes
3. Use configurator to configure parent product

**Expected behavior**
The configurator should recognize that the component does not require the custom attribute and disregard the custom values coming in.

**Additional context**
This should be fixed by disregarding custom attributes that do not apply to the component in the validate_configuration function.

**Comment by andreampiovesana** [comment]
I think that custom values should be stored in product.product, not only in sessions.
If 2 sessions have same attribute values but different custom values the result should be 2 product.product: this simplify the configuration in bom explosion.

**Comment by theangryangel** [comment]
As far as I can tell this was originally in the module and then this was changed to travel in the configuration instead.

To my eye it looks like it was changed across a few commits. I've pasted a link to a few of them below. I haven't got the full commit list.

* https://github.com/OCA/product-configurator/commit/d3021dd993c5fe73f4ec942977d9878c149d53c5
* https://github.com/OCA/product-configurator/commit/185f330afece3ada95f469038e2821f1c1af05a8
* https://github.com/OCA/product-configurator/commit/4e60ebf9c994298f002bc567900998e67c843489

I would assume that there's a fundamental design decision there, but I'm struggling to find the reasoning. @bizzappdev can you help explain why? I'm assuming it's to avoid DB bloat or something like that? 

I think the part a lot of us are struggling to understand is that a 2 metre hose (for example) would be fundamentally different from a 5 metre hose, and then how that surfaces and is dealt with as part of the stock system. 

It almost seems like the intention was to plug product.config.session into the procurement system (i.e. passing it from sale.order to stock.picking to mrp.production, etc.), but that seems to be missing?
